microsoft/document-generation-solution-accelerator

.github/workflows/docker-build-and-push.yml

updated workflow

---

.github/pull_request_template.md

New Template Created for better understanding.

 Template Updated

---

frontend/src/pages/chat/Chat.tsx

[SmokeTesting] - Docgen - While switching from Browse to Generate section, on Generate section vertical scroll starts to move from top to bottom by default.* ...
Repro Steps:
Deploy Document Generation
there should be history in Generate section
now switch back to Browse section 
and click on generate section tab
observe the behavior of vertical scroll bar movement.
Actual: after switching from browse to generate section, vertical scroll bar on generate tab starts moving from top to bottom. 
Expected: after switching from browse to generate section, vertical scroll bar should point to bottom of last question/response. 

`fix`: While switching from Browse to Generate section, on Generate section vertical scroll starts to move from top to bottom by default.

---

.flake8
.github/workflows/pylint.yml
.pylintrc
requirements.txt

* ...
* Added the config file to implement the pylint in entire code .

Add linting configuration files

---

.github/workflows/docker-build-and-push.yml

This pull request includes a small change to the `.github/workflows/docker-build-and-push.yml` file. The change adds the `workflow_dispatch` event to trigger the workflow manually.
* [`.github/workflows/docker-build-and-push.yml`](diffhunk://#diff-4c9cc7fae5379a513fa294daa6c13154c0c512e832a10d7ff36a651aa54129f5R14): Added `workflow_dispatch` to the list of events that trigger the workflow.

ci: Update docker-build-and-push.yml

---

infra/main.bicep

fix: - model version name

---

frontend/src/api/api.ts
frontend/src/components/ChatHistory/ChatHistoryList.test.tsx
frontend/src/components/ChatHistory/ChatHistoryListItem.tsx
frontend/src/components/ChatHistory/ChatHistoryPanel.test.tsx
frontend/src/components/ChatHistory/ChatHistoryPanel.tsx
frontend/src/components/DraftCards/SectionCard.test.tsx
frontend/src/components/Sidebar/Sidebar.test.tsx
frontend/src/pages/chat/Chat.tsx
frontend/src/pages/layout/Layout.tsx
frontend/src/state/AppProvider.tsx
frontend/src/state/AppReducer.tsx
frontend/src/test/test.utils.tsx
start.cmd

This pull request includes several changes to improve the chat functionality and refactor how chat history is fetched in the application. Chat History is being fetched only when the user clicks on the history button and not on the web page load, which in turn doesn't block the chat interface.
* [`frontend/src/pages/chat/Chat.tsx`](diffhunk://#diff-acfbdb512c79eb9c53d0c2488f520793646422af0dac0a8c83b6c5080ffe784aR425-R427): Added fallback logic to use `currentChat` if a conversation is not found in `chatHistory` when fetching a conversation by ID. [[1]](diffhunk://#diff-acfbdb512c79eb9c53d0c2488f520793646422af0dac0a8c83b6c5080ffe784aR425-R427) [[2]](diffhunk://#diff-acfbdb512c79eb9c53d0c2488f520793646422af0dac0a8c83b6c5080ffe784aR466-R468) …

fix: fetch history on button click and not on web page load

---

src/frontend/src/components/ChatHistory/chatHistoryListItem.test.tsx
src/frontend/src/pages/chat/Chat.test.tsx
src/frontend/src/pages/document/Document.test.tsx
src/frontend/src/pages/draft/Draft.test.tsx

This pull request includes several updates to the unit tests for various components in the frontend. The changes primarily focus on improving the accuracy and reliability of the tests by adding new mock implementations and adjusting existing test cases.
* Added `historyRead` to the list of mocked API functions in `chatHistoryListItem.test.tsx`. [[1]](diffhunk://#diff-59d2223250adfb8fe31a3dfde0079d9843c3a37c77cac884ca3edc7fe09a44dfL4-R4) [[2]](diffhunk://#diff-59d2223250adfb8fe31a3dfde0079d9843c3a37c77cac884ca3edc7fe09a44dfR14)
* Updated test cases to include new scenarios and ensure the `onSelect` handler is called with the correct data, including messages fetched via `historyRead`. [[1]](diffhunk://#diff-59d2223250adfb8fe31a3dfde0079d9843c3a37c77cac884ca3edc7fe09a44dfL167-R200) …

fix: fix document test

---

README.md
infra/deploy_cosmos_db.bicep

* This pull request includes updates to the `README.md` file to correct URLs and improve clarity in the deployment instructions.
Documentation updates:
* Updated the URL in the "Azure Products by Region" section to point to the correct page.
* Clarified quota recommendations by specifying the model names and their respective capacities.
Verify that the following are valid-NA

docs: correct URLs and improve clarity in the deployment instructions

---

infra/main.bicep
infra/main.json

* This pull request includes changes to the `infra` directory to update resource parameters and configurations in the `main.bicep` and `main.json` files. The most important changes include extending the maximum length of the `environmentName` parameter and modifying the `disableLocalAuth` setting for database accounts.
Parameter updates:
* [`infra/main.bicep`](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L5-R5): Extended the maximum length of the `environmentName` parameter from 10 to 20 characters.
* [`infra/main.json`](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L8-R15): Extended the maximum length of the `environmentName` parameter from 10 to 20 characters to match the change in `main.bicep`.
Configuration …

fix: Environment name min length updated to 20

---

azure.yaml
infra/deploy_ai_foundry.bicep
infra/deploy_app_service.bicep
infra/deploy_cosmos_db.bicep
infra/deploy_keyvault.bicep
infra/deploy_managed_identity.bicep
infra/deploy_post_deployment_scripts.bicep
infra/deploy_storage_account.bicep
infra/main.bicep
infra/main.json

This pull request includes significant changes to the naming conventions in multiple infrastructure files to improve consistency and readability. Additionally, it introduces post-provision hooks in the `azure.yaml` file.
* [`infra/deploy_ai_foundry.bicep`](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626L13-R28): Updated various resource names to use a consistent prefix format. For example, `storageName` changed from `${solutionName}hubstorage` to `st${solutionName}hub`, and `aiServicesName` changed from `${solutionName}-aiservices` to `ais-${solutionName}`.
* [`infra/deploy_app_service.bicep`](diffhunk://#diff-37c8b5694d17291d641a19fb8a562e30642066b4bf8b8657f2636f50567cf4ebL15-R26): Modified resource names to follow the new naming convention. For …

refactor: update naming conventions for resources in Bicep files

---

.devcontainer/devcontainer.json

* ...
This pull request includes a modification to the `.devcontainer/devcontainer.json` file to enhance the post-start command by adding an additional step.
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L19-R19): Updated the `postStartCommand` to include a command that changes the permissions of the `quota_check_params.sh` script to make it executable.
No

feat: add permission for quota_check_params.sh in dev container

---

.gitignore
README.md
azure.yaml
infra/main.bicep
infra/main.json
infra/scripts/copy_kb_files.sh
infra/scripts/process_sample_data.sh
infra/scripts/run_create_index_scripts.sh

fix: Template deployment

---

src/frontend/src/components/ChatHistory/ChatHistoryListItem.tsx
src/frontend/src/components/ChatHistory/chatHistoryListItem.test.tsx

This pull request includes changes to the `ChatHistoryListItemCell` component and its associated tests to improve user interaction and error handling. The most important changes include adding conditions to prevent actions during edit mode, updating button states based on title changes, and refining test cases to align with the new logic.
Improvements to user interaction:
* [`src/frontend/src/components/ChatHistory/ChatHistoryListItem.tsx`](diffhunk://#diff-67811b1ba83ed2ecef29fb365da49305e6a7330370b3d827ab8869b4716f4f37L228-R235): Added conditions to prevent `handleSelectItem` from being triggered during edit mode and to stop event propagation when editing. [[1]](diffhunk://#diff-67811b1ba83ed2ecef29fb365da49305e6a7330370b3d827ab8869b4716f4f37L228-R235) …

fix: DocGen- Save action triggers error when no changes are made to template title

---

.github/dependabot.yml

* This pull request includes updates to the `.github/dependabot.yml` file to correct the directories for both frontend and backend dependencies.
Directory updates for dependabot:
* Changed the directory for the frontend dependencies from `/frontend` to `/src/frontend` to reflect the correct path.
* Changed the directory for the backend dependencies from `/` to `/src/backend` to reflect the correct path.

fix: Update dependabot.yml path 

---

src/.dockerignore

- This PR renames `WebApp.dockerignore` to `.dockerignore` to ensure it is recognized by the Docker CLI during image build.
- The `.dockerignore` file prevents unnecessary files and directories (e.g., node_modules, .venv, etc.) from being sent to the Docker daemon as part of the build context, which improves build performance and keeps image sizes smaller.
- Verify that the .dockerignore file is correctly recognized during the Docker build and the intended files are excluded

fix: Rename Docker ignore file to standard .dockerignore

---

.devcontainer/devcontainer.json
.devcontainer/setup_env.sh
.gitignore
.vscode/launch.json
README.md
azure.yaml
docs/README_LOCAL.md
infra/scripts/copy_kb_files.sh
infra/scripts/process_sample_data.sh
infra/scripts/run_create_index_scripts.sh
src/start.sh

This pull request introduces several updates to improve the development environment, streamline deployment processes, and enhance script robustness. Key changes include updates to the dev container configuration, adjustments to deployment scripts, and documentation improvements.
* Updated `.devcontainer/devcontainer.json` to replace `postStartCommand` with `postCreateCommand`, which now runs a new `setup_env.sh` script for environment setup. Added Node.js, Azure CLI, and Azure Dev CLI features for enhanced tooling. (`[[1]](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L6-R20)`, `[[2]](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L19-R33)`)
* Created a new `setup_env.sh` script to fetch the latest code and set up …

fix: fixed dev container, start.sh and refactored post deployment scripts

---

src/frontend/src/pages/draft/Draft.test.tsx
src/frontend/src/pages/draft/Draft.tsx

Document gets generated without title, if title is not added pre-export.
- Ask "Generate promissory note with a proposed $100,000 for Washington State" in "Generate" section
- Once proper response is generated, click on generate draft arrow to go to the draft section
- The same asked question will appear as a title in draft section
- Switch back to the generate section
- Refresh the screen and ask the same question again "Generate promissory note with a proposed $100,000 for Washington State"
- Now before moving to the draft section
- Ask it to "Remove Amendments Promissory Note" in "Generate" section
- Now move to the draft section by clicking on "generate draft arrow"
- Now observe there is no default title under title section.

fix: Document gets generated without title, if title is not added pre-export.

---

.github/workflows/Scheduled-Dependabot-PRs-Auto-Merge.yml

* Removing the approving step as its not required from Scheduled Dependabot PRs Auto-Merge yml file

chore: Removed approval step from Scheduled Dependabot PRs Auto-Merge

---

.github/workflows/deploy.yml
docs/QuotaCheck.md
scripts/quota_check_params.sh

* ...
This pull request updates the default capacities for AI models, adjusts environment variables in the deployment workflow, and ensures documentation reflects these changes. The most important changes include modifying model capacities, adding a new environment variable for deployment location, and updating scripts and documentation to align with the new capacities.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L17-R18): Reduced `GPT_MIN_CAPACITY` from 250 to 150 and increased `TEXT_EMBEDDING_MIN_CAPACITY` from 40 to 80. Added `AZURE_LOCATION` as a new environment variable for AI deployments. [[1]](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L17-R18) …

fix: update GPT model capacity and fix aiDeploymentsLocation issue

---

src/tests/unit_tests/helpers/test_azure_credential_utils.py

This pull request introduces unit tests for the `get_azure_credential` and `get_azure_credential_async` functions in the `azure_credential_utils` module. The tests cover both synchronous and asynchronous scenarios, ensuring the functions behave correctly in different environments (development and non-development).
* **Synchronous Tests**:
- Added `test_get_azure_credential_dev_env` to verify that `get_azure_credential` uses `DefaultAzureCredential` in a development environment.
- Added `test_get_azure_credential_non_dev_env` to verify that `get_azure_credential` uses `ManagedIdentityCredential` in a non-development environment.
* **Asynchronous Tests**:
- Added `test_get_azure_credential_async_dev_env` to verify that `get_azure_credential_async` uses `AioDefaultAzureCredential` in a …

feat: Added unit tests for Azure credential utilities

---

infra/main.bicep

* This pull request introduces significant improvements to the Azure infrastructure deployment scripts, focusing on standardizing parameter names, supporting resource tagging, and enhancing output variables for better integration and management. The changes primarily update the Bicep templates and deployment workflows to align with best practices, improve maintainability, and provide more flexibility for resource configuration.
**Key changes include:**
- Standardized parameter names across Bicep modules (e.g., `solutionName`, `hostingPlanName`, `websiteName`) and added descriptions to improve clarity and consistency in `infra/deploy_ai_foundry.bicep`, `infra/deploy_app_service.bicep`, and related files. [[1]](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626 …

feat: Docgen Bicep Standard Changes - vars

---

infra/main.bicep

This pull request adds a small enhancement to the resource group tagging logic in the `infra/main.bicep` deployment template. The change introduces a new tag to help identify which user deployed the resources.
Resource tagging improvement:
* Added a `CreatedBy` tag to the resource group tags, using the deployer's username extracted from their user principal name.
* ...

chore: Bicep changes to add  Created By tag while deployment
