infrastructure/deployment.json

- Added Log Analytics workspace for App Insights resource. Classic App Insights no longer supported in some regions.

Added Log Analytics workspace for App Insights

---

frontend/src/components/Sidebar/Sidebar.module.css
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/pages/chat/Chat.tsx
frontend/src/state/AppProvider.tsx
frontend/src/state/AppReducer.tsx

Reverts microsoft/Generic-Build-your-own-copilot-Solution-Accelerator#84

Revert "fix: Psl bug 7819"

---

backend/settings.py

We are reverting this prompt change as we are facing issue during the draft creation.

Revert | System prompt related to tabular prompt

---

requirements.txt

The Quart package was having an issue with the version 0.19.4 and application was not loading.
Upgraded the Quart version and below are some links to reference.
https://github.com/pallets/quart/issues/371
https://github.com/pallets/flask/issues/5642

Package Update | Quart update from 0.19.4 to 0.19.9

---

requirements.txt

Updated the OpenAI package version from 1.6.1 to 1.55.3 to ensure compatibility with specific requirements or resolve issues related to the newer version
- open ai | 1.6.1 to 1.55.3

Updated OpenAI Package Version from 1.6.1 to 1.55.3

---

.github/workflows/docker-build-and-push.yml

Implementation of separate containers for Prod, Dev, and Demo Environments
We have added separate image tog for prod, dev and demo environments.

feat: Implementation of separate containers for Prod, Dev, and Demo Environments

---

.github/CODEOWNERS

The Codeowners file was missing in the .github folder. Created the Codeowners file and added a default owner to the repository

CodeOwner File Addition

---

.github/workflows/deploy.yml
.github/workflows/tests.yml

…k deployment validation process.
* ...

Unit Tests and One-Click Deployment Validation Pipeline

---

frontend/package-lock.json

Reverts microsoft/Generic-Build-your-own-copilot-Solution-Accelerator#75

build: Revert "Bump rollup from 3.29.4 to 3.29.5 in /frontend"

---

requirements.txt

Reverts microsoft/Generic-Build-your-own-copilot-Solution-Accelerator#102

build: Revert "Bump aiohttp from 3.10.5 to 3.10.11"

---

frontend/package.json
frontend/src/components/Answer/Answer.tsx
frontend/src/pages/chat/Chat.tsx

fix : updated code and update package.json file

---

.github/workflows/stale-bot.yml

Implemented a pipeline for stale bot-doc gen

---

README.md

To let end users know update sample data if they are planning to use Promissory note data.
To let end users know update sample data if they are planning to use Promissory note data.

docs: Update README.md for updating the sample Promissory Note data

---

.github/workflows/docker-build-and-push.yml

Building and pushing the docker conditionally

ci: Docker image yml file updated for building conditionally 

---

.github/workflows/deploy.yml
.github/workflows/docker-build-and-push.yml
.github/workflows/pr-title-checker.yml
.github/workflows/pylint.yml
.github/workflows/stale-bot.yml
.github/workflows/tests.yml

This pull request includes several changes to the GitHub Actions workflow files to improve clarity and scheduling. The most important changes include renaming workflows for consistency and adjusting the cron schedules.
Renaming workflows for consistency:
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L1-R8): Renamed workflow from "CI-Validate Deployment" to "Validate Deployment" and adjusted the cron schedule to run at 9:00 AM and 9:00 PM GMT.
* [`.github/workflows/docker-build-and-push.yml`](diffhunk://#diff-4c9cc7fae5379a513fa294daa6c13154c0c512e832a10d7ff36a651aa54129f5L1-R1): Renamed workflow from "Build and Push Docker Image" to "Build Docker and Optional Push".
* …

chore: Updated workflow names and trigger schedule

---

README.md
docs/README_LOCAL.md
docs/TRANSPARENCY_FAQ.md

update the content "README.md, docs/README_LOCAL.md, docs/TRANSPARENCY_FAQ.md"

docs: replace Studio and Open AI

---

.github/CODEOWNERS

* This pull request includes a small change to the `.github/CODEOWNERS` file. The change adds two new team members, `@Vinay-Microsoft` and `@malrose07`, to the list of default owners for the repository.

chore: adds two new team members in CODE OWNERS

---

infra/main.json

* This pull request includes updates to the `infra/main.json` file to reflect changes in the template hash and the GPT model version.
Updates in `infra/main.json`:
* Updated the `templateHash` value to a new hash.
* Updated the `gptModelVersion` to "2024-05-01-preview".

fix: Model version update in main.json

---

.github/workflows/azure-dev.yml
azure.yaml
infra/deploy_app_service.bicep

feat - azure search params and github pipeline variable changes

---

.azdo/pipelines/azure-dev.yml
.devcontainer/devcontainer.json
.github/workflows/azure-dev.yml

refactor - azd pipeline changes

---

infra/deploy_app_service.bicep
infra/deploy_storage_account.bicep
infra/main.json

Azd pipeline

---

infra/deploy_app_service.bicep

search env added

---

infra/deploy_keyvault.bicep
infra/main.bicep
infra/main.json
infra/scripts/index_scripts/01_create_search_index.py
infra/scripts/index_scripts/02_process_data.py
infra/scripts/run_create_index_scripts.sh

fix: update deployment

---

app.py
frontend/src/pages/document/Document.tsx
infra/deploy_app_service.bicep
infra/main.bicep
infra/main.json
infra/scripts/index_scripts/01_create_search_index.py

1. Added default values for search related env variables in app service
2. Updated "sourceurl" field in search index to Searchable and made minor changes in citation code to match latest index fields.
Improvements to search functionality:
* [`app.py`](diffhunk://#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959L915-R915): Changed the search query parameter from `filepath` to `sourceurl` to align with the updated indexing strategy.
* [`frontend/src/pages/document/Document.tsx`](diffhunk://#diff-23ca5b98791dd8664df8f49a058b2ed80fa108f14cdf2f78078d281ff878820bL42-R42): Updated the document content display to use `document.content` instead of `document.full_content`.
Azure Search configuration updates:
* [`infra/deploy_app_service.bicep`](diffhunk://#diff-37c8b5694d17291d6 …

fix: added app service env variable values and made "sourceurl" index field as searchable to show citations

---

README.md
docs/AzureAccountSetUp.md
docs/AzureSemanticSearchRegion.md
docs/CustomizingAzdParameters.md
docs/DeleteResourceGroup.md

docs: update readme

---

README.md
docs/TRANSPARENCY_FAQ.md

Updating readme to reflect name change

docs-readme-update

---

docs/quota_check.md

* This pull request includes updates to the `docs/quota_check.md` file to correct URLs for quota check scripts. These changes ensure that the scripts are fetched from the correct repository, which is `document-generation-solution-accelerator`.
Documentation updates:
* [`docs/quota_check.md`](diffhunk://#diff-e017fb8974388f6f46533aad2e78f0f491aa0b3dc6885732e264562e8a55f16bL19-R27): Updated URLs for `quota_check_params.sh` and `quota_check_all_regions.sh` to point to the `document-generation-solution-accelerator` repository.

docs: Update quota_check.md

---

scripts/quota_check_all_regions.sh
scripts/quota_check_params.sh

* This pull request includes updates to two scripts that handle quota checks. The changes add helpful instructions for users to request a quota increase when necessary.
Enhancements to user instructions:
* [`scripts/quota_check_all_regions.sh`](diffhunk://#diff-c8066c757e48ef56ffe732fd1c318557e82c96cdb2b98be7182db42af7ebc0a1R91): Added a message with a link to request a quota increase at the end of the script.
* [`scripts/quota_check_params.sh`](diffhunk://#diff-7074fae63115e7abe9a9840899b95bc6d2ce674fe1224ed28cc8e69ca4745502R125): Added a message with a link to request a quota increase when there is insufficient quota for a model in a region.

docs:  helpful instructions for users to request a quota increase when necessary

---

README.md

* This pull request includes updates to the `README.md` file to improve clarity and streamline deployment options. The most important changes include renaming sections for better understanding, removing redundant deployment options, and commenting out unnecessary sections.
Improvements to documentation clarity:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L3-R3): Renamed "ONE-CLICK DEPLOY" to "QUICK DEPLOY" and "SUPPORTING DOCUMENTS" to "SUPPORTING DOCUMENTATION" for better clarity.
Streamlining deployment options:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L152-R163): Commented out the redundant "Deploy with Bicep/ARM template" section to simplify the deployment instructions.
* …

docs:  updates to the `README.md` file to improve clarity and streamline deployment options

---

.devcontainer/devcontainer.json

* This pull request includes a change to the `.devcontainer/devcontainer.json` file to ensure that the `postStartCommand` is executed after the container starts.
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L19-R19): Enabled the `postStartCommand` to run `git pull origin main` and install Python dependencies from `infra/scripts/index_scripts/requirements.txt`.
Verify that the following are valid - NA

fix: Change to the `.devcontainer/devcontainer.json` file to ensure that the `postStartCommand` is executed after the container starts.

---

.github/workflows/deploy.yml
README.md
docs/CustomizingAzdParameters.md
infra/main.bicep
infra/main.json

* This pull request includes several changes aimed at updating deployment configurations and documentation to reflect the new `GlobalStandard` deployment type and the `gpt-4o` model. The most important changes include modifications to deployment parameters, documentation updates, and version updates for the Bicep template.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L118-R119): Changed `deploymentType` to `GlobalStandard` and `gptModelName` to `gpt-4o`.
* [`infra/main.bicep`](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L28-R36): Updated default values for `deploymentType` to `GlobalStandard` and `gptModelName` to `gpt-4o`.
* …

ci: model back to gpt4o due to more availability regions

---

package-lock.json
src/frontend/src/components/ChatHistory/ChatHistoryList.test.tsx
src/frontend/src/components/ChatHistory/ChatHistoryListItem.tsx
src/frontend/src/components/ChatHistory/chatHistoryListItem.test.tsx
src/start.cmd

This pull request includes several changes to the `ChatHistoryListItem` component and adjustments to the startup script. The changes enhance tooltip functionality, adjust title truncation, and correct paths in the startup script.
Enhancements to `ChatHistoryListItem` component:
* Added `TooltipHost` and `DirectionalHint` imports to `src/frontend/src/components/ChatHistory/ChatHistoryListItem.tsx`.
* Defined `tooltipStyles` for the `TooltipHost` component.
* Adjusted title truncation length from 28 to 24 characters.
* Wrapped the title in a `TooltipHost` to display the full title on hover and adjusted the layout.
Adjustments to startup script:
* Corrected the path for restoring backend Python packages in `src/start.cmd`.
* Corrected the path for restoring frontend npm packages in …

fix: resolved DocGen- After hovering over the chat history, no tooltip is displayed

---

infra/main.bicep
infra/main.json

* This pull request includes changes to the `infra/main.bicep` and `infra/main.json` files to update the description of the `environmentName` parameter. The description now reflects that the prefix length should be 3-20 characters long instead of 3-10 characters long.
Updates to parameter descriptions:
* [`infra/main.bicep`](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L6-L10): Updated the description for the `environmentName` parameter to specify that the prefix length should be 3-20 characters long.
* [`infra/main.json`](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L17-R17): Updated the description for the `environmentName` parameter to specify that the prefix length should be 3-20 characters long.
Metadata updates: …

fix: updated the description for environment name

---

src/frontend/src/pages/chat/Chat.tsx

* Fixed the multiple scrollbars issue on reference content modal

fix: resolved multiple scrollbar issue

---

scripts/quota_check_params.sh

* ...
This pull request includes changes to the `scripts/quota_check_params.sh` file to enhance the handling of Azure subscriptions. The main improvements involve fetching available Azure subscriptions and allowing the user to select one if multiple subscriptions are found.
Improvements to Azure subscription handling:
* Added a process to fetch available Azure subscriptions and count them.
* Automatically selects the subscription if only one is available.
* Prompts the user to choose a subscription if multiple subscriptions are found, with validation for user input.
* Sets the selected subscription and displays the active subscription details.
No

fix: updated the subscription code in the script

---

src/frontend/src/components/ChatHistory/ChatHistoryList.test.tsx
src/frontend/src/components/ChatHistory/ChatHistoryPanel.test.tsx
src/frontend/src/components/DraftCards/SectionCard.test.tsx
src/frontend/src/components/DraftCards/SectionCard.tsx
src/frontend/src/components/Sidebar/Sidebar.test.tsx
src/frontend/src/pages/draft/Draft.test.tsx
src/frontend/src/pages/draft/Draft.tsx
src/frontend/src/state/AppProvider.tsx
src/frontend/src/state/AppReducer.tsx
src/frontend/src/test/test.utils.tsx

* Doc Gen - Generate Document button remains enabled when response is loading.
- [x ] No

fix: psl bug 16193

---

README.md
azure.yaml
docs/PowershellSetup.md
infra/deploy_ai_foundry.bicep
infra/main.bicep
infra/main.json
infra/scripts/add_cosmosdb_access.sh
infra/scripts/process_sample_data.sh
infra/scripts/run_create_index_scripts.sh

This pull request includes several changes aimed at enhancing the deployment process, improving documentation, and updating scripts for better functionality. The most important changes include updates to the deployment scripts to handle CosmosDB access, modifications to the `README.md` for better clarity, and the addition of a new setup guide for PowerShell.
* Updated `infra/main.bicep` to output `COSMOSDB_ACCOUNT_NAME` and `RESOURCE_GROUP_NAME` for use in scripts.
* Modified `infra/scripts/process_sample_data.sh` to include CosmosDB account name and resource group name as parameters, and added a call to `add_cosmosdb_access.sh` for assigning the necessary role.
* Added `infra/scripts/add_cosmosdb_access.sh` to handle role assignment for CosmosDB access.
* Updated `README.md` to include …

fix: added script for Cosmos DB role assignment and few Readme updates

---

docs/quota_check.md

docs: update quota_check

---

.github/workflows/deploy.yml

* ...
This pull request includes significant updates to the deployment workflow in the `.github/workflows/deploy.yml` file. The main changes involve extracting AI Services and Key Vault names, updating the resource deletion process, and handling the soft deletion and purging of these resources.
* **Extract AI Services and Key Vault Names:**
- Added steps to fetch and store the names of AI Services and Key Vault before deletion. This ensures that these names are available for subsequent steps.
* **Update Resource Deletion Process:**
- Modified the waiting logic for resource deletion to include AI Services. This change ensures that the workflow waits for all relevant resources, including AI Services, to be deleted.
* **Wait for Soft Deletion:**
- Introduced steps to wait for the soft …

ci: fix ai service deletion login in cleaning setup

---

infra/deploy_app_service.bicep
infra/main.bicep
infra/main.bicepparam

This pull request includes several changes to the `infra` directory, primarily focusing on parameterizing the solution location and ensuring consistency across various Bicep files. The most important changes include the addition of the `solutionLocation` parameter, updates to resource locations, and modifications to deployment modules.
Parameterization and consistency improvements:
* [`infra/deploy_app_service.bicep`](diffhunk://#diff-37c8b5694d17291d641a19fb8a562e30642066b4bf8b8657f2636f50567cf4ebL9-R10): Added the `solutionLocation` parameter and updated the resource locations to use this parameter instead of `resourceGroup().location`. [[1]](diffhunk://#diff-37c8b5694d17291d641a19fb8a562e30642066b4bf8b8657f2636f50567cf4ebL9-R10) …

feat: added feature to use azure_location environment variable for deployment with Fallback to resource group location

---

infra/deploy_keyvault.bicep
infra/main.json

* Pipeline Deployment keyvault purge protection is disabled by default to delete keyvault service.

fix: key vault purge issue fix

---

README.md
docs/DeploymentGuide.md

docs: readme and deployment guide updates

---

.github/workflows/deploy.yml

This pull request updates the `.github/workflows/deploy.yml` file to improve flexibility and reliability in the deployment process. Key changes include introducing environment variables for resource capacities, modifying deployment parameters, and adjusting conditional logic for better error handling.
* Added `GPT_MIN_CAPACITY` and `TEXT_EMBEDDING_MIN_CAPACITY` as environment variables to centralize configuration. These are now used in deployment scripts instead of hardcoded values. [[1]](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R10-R13) [[2]](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L33-R38)
* Changed the `secondaryLocation` parameter from `eastus2` to `northcentralus` for improved regional distribution.
* …

fix: fix deployment pipeline

---

src/frontend/src/pages/draft/Draft.test.tsx
src/frontend/src/pages/draft/Draft.tsx

Document gets generated without title, if title is not added pre-export.
- Ask "Generate promissory note with a proposed $100,000 for Washington State" in "Generate" section
- Once proper response is generated, click on generate draft arrow to go to the draft section
- The same asked question will appear as a title in draft section
- Switch back to the generate section
- Refresh the screen and ask the same question again "Generate promissory note with a proposed $100,000 for Washington State"
- Now before moving to the draft section
- Ask it to "Remove Amendments Promissory Note" in "Generate" section
- Now move to the draft section by clicking on "generate draft arrow"
- Now observe there is no default title under title section.

fix: Document gets generated without title, if title is not added pre-export.

---

.github/dependabot.yml
.github/workflows/Scheduled-Dependabot-PRs-Auto-Merge.yml

* Introduced a scheduled GitHub Actions workflow to auto-approve and auto-merge Dependabot PRs targeting the dependabotchanges branch.
* Also optimized the dependabot.yml configuration to group dependency updates by ecosystem and path, significantly reducing PR noise.

chore: add scheduled auto-merge workflow and group Dependabot PRs by ecosystem

---

infra/deploy_ai_foundry.bicep
infra/deploy_app_service.bicep
infra/main.bicep
src/app.py
src/event_utils.py

* ...
This pull request introduces comprehensive telemetry enhancements and logging improvements to the `src/app.py` file. The changes aim to integrate Application Insights for monitoring, add detailed event tracking throughout the application, and improve logging for better observability and debugging. Below is a summary of the most important changes grouped by theme:
* Configured Application Insights using the `APPLICATIONINSIGHTS_CONNECTION_STRING` environment variable. Added logging to indicate whether the configuration was successful or skipped. Suppressed unnecessary logs from Azure and OpenTelemetry libraries. (`[src/app.pyR23-R51](diffhunk://#diff-04791d82dd15fdd480f084d7ef65a10789fa5012cb7935f76080763444d48a00R23-R51)`)
* Added `track_event_if_configured` calls to log important …

feat: added open telemetry logs

---

.github/workflows/docker-build-and-push.yml

* ...
This pull request updates the `.github/workflows/docker-build-and-push.yml` file to improve the handling of secrets for registry URLs by providing default values. 
* Updated the `jobs:` section to include default values (`'acrlogin.azurecr.io'`) for `ACR_LOGIN_SERVER` and `ACR_DEV_LOGIN_SERVER` in case the secrets are not set. This ensures the workflow can proceed without failure due to missing secrets.

fix: tag not found error

---

.github/workflows/Scheduled-Dependabot-PRs-Auto-Merge.yml

* Enhanced rebase logic to handle merge conflicts using --strategy-option=theirs.
* Implemented multi-strategy auto-merge (merge, squash, rebase) with fallback handling.
* Improved overall script reliability and compatibility with repo-level merge restrictions.

chore: enhanced the scheduled dependabot auto pr merge workflow

---

src/requirements.txt

This pull request updates the `src/requirements.txt` file to include dependencies related to OpenTelemetry and Azure Monitor for enhanced observability and monitoring capabilities.
Dependency additions:
* Added OpenTelemetry exporters for both gRPC and HTTP protocols: `opentelemetry-exporter-otlp-proto-grpc` and `opentelemetry-exporter-otlp-proto-http`.
* Included OpenTelemetry SDK and API dependencies: `opentelemetry-sdk==1.31.1` and `opentelemetry-api==1.31.1`.
* Added OpenTelemetry semantic conventions and instrumentation libraries: `opentelemetry-semantic-conventions==0.52b1` and `opentelemetry-instrumentation==0.52b1`.
* Introduced Azure Monitor-specific dependencies: `azure-monitor-events-extension` and `azure-monitor-opentelemetry==1.6.8`.

fix: add OpenTelemetry dependencies to requirements.txt

---

docs/CustomizingAzdParameters.md
docs/DeploymentGuide.md
infra/deploy_ai_foundry.bicep
infra/main.bicep
infra/main.bicepparam
infra/main.json

feat: Implemented reusing of log analytics service

---

infra/deploy_ai_foundry.bicep
infra/main.bicep
infra/main.bicepparam
infra/main.json

* GPT-4 model deployment issue fixed. Issue with the version of the GPT model being deployed has been resolved by parameterizing the model version.

fix: parameterized for model version

---

infra/deploy_ai_foundry.bicep

* Fixed the issue to reuse log analytics across different subscriptions in same tenant

fix: To reuse Log Analytics across subscriptions

---

docs/AppAuthentication.md
docs/create_new_app_registration.md

* Updated App authentication and added create new app registration .md file.
Added create new app registration .md file
Updated AppAuthentication.md

docs: AppAuthentication update

---

docs/CustomizingAzdParameters.md
docs/DeploymentGuide.md
infra/main.bicepparam

This pull request introduces updates to improve parameter customization and deployment configuration documentation, as well as adds new configurable parameters in the infrastructure code. The changes aim to enhance clarity, usability, and flexibility for users managing Azure deployments.
* [`docs/CustomizingAzdParameters.md`](diffhunk://#diff-6eec6ba43f4d3beb5835ad60e22b6974f1224c7b5ff024f690cd9549e8b4aec7L6-R37): Updated the parameter customization section to include a detailed table of configurable parameters, their types, example values, and purposes. Simplified instructions for setting parameters with a consistent command format. Removed redundant examples and replaced them with a single general example.
* [`docs/DeploymentGuide.md`](diffhunk://#diff-5a9feaaa3fe70489e88e08725db341b9daf …

feat: Standardize Bicep Parameters for DocGen

---

.github/workflows/python-app.yml
.github/workflows/tests.yml

This pull request makes adjustments to the testing configurations in the workflow files to ensure tests are run specifically in the `./src/tests` directory. These changes improve the accuracy and scope of test execution by explicitly targeting the correct test directory.
Updates to test configurations:
* [`.github/workflows/python-app.yml`](diffhunk://#diff-d7b3e1cc0b909c52439e5d8d3f602f70644d0f6b62a54825968d819f7a5bee89L32-R32): Modified the pytest command in both Linux and Windows jobs to include the `./src/tests` directory, ensuring tests are run from the correct location. [[1]](diffhunk://#diff-d7b3e1cc0b909c52439e5d8d3f602f70644d0f6b62a54825968d819f7a5bee89L32-R32) [[2]](diffhunk://#diff-d7b3e1cc0b909c52439e5d8d3f602f70644d0f6b62a54825968d819f7a5bee89L50-R50)
* …

test: fixed test pipeline

---

docs/DeploymentGuide.md

This pull request simplifies the deployment guide by removing outdated instructions for deploying in an existing Azure Resource Group. The change improves clarity and reduces redundancy in the documentation.
Documentation updates:
* [`docs/DeploymentGuide.md`](diffhunk://#diff-5a9feaaa3fe70489e88e08725db341b9dafb6a4185d382bba81c4093aaaded7cL137-L161): Removed the section detailing how to deploy in an existing Azure Resource Group, including steps to identify the resource group, set it in the environment, and continue deployment. This streamlines the guide and avoids duplicating information.

docs: remove deployment instructions for using an existing RG

---

docs/re-use-log-analytics.md

docs: Link update for re-use-log-analytics.md

---

azure.yaml
docs/DeploymentGuide.md

This pull request updates version requirements for the Azure Developer CLI (`azd`) in the `azure.yaml` configuration file and the deployment guide documentation. These changes ensure consistency in version specifications and clarify the minimum required version for users.
* ...

docs: added required azd version in azure.yml file and updated DeploymentGuide.md file

---

.github/workflows/deploy.yml
.github/workflows/docker-build-and-push.yml

This pull request makes updates to the `.github/workflows/deploy.yml` file to enhance the deployment workflow. The changes primarily focus on improving branch name resolution and adding steps to the post-deployment script.
* Updated the `BRANCH_NAME` environment variable to use `github.event.workflow_run.head_branch` as the primary source for branch name resolution, ensuring compatibility with workflow runs triggered by other workflows. (`[.github/workflows/deploy.ymlL19-R19](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L19-R19)`)
* Added a missing parameter (`RESOURCE_GROUP_NAME`) to the `run_create_index_scripts.sh` script call, ensuring the script receives all required inputs. (`[.github/workflows/deploy.ymlR184-R194](diffhunk://#diff-28802fbf11c83a2e …

ci: fix post deployment script issue in deploy workflow

---

infra/deploy_ai_foundry.bicep
infra/main.bicep
infra/main.json
scripts/checkquota.sh
scripts/quota_check_params.sh

* ...
This pull request updates references to the `text-embedding-ada-002` model to use the `GlobalStandard` variant instead of the `Standard` variant across multiple files. It ensures consistency in model usage and aligns configurations with the updated naming convention.
* [`infra/main.bicep`](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L23-R23): Changed the usage name for `text-embedding-ada-002` from `OpenAI.Standard.text-embedding-ada-002` to `OpenAI.GlobalStandard.text-embedding-ada-002`.
* [`infra/main.json`](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L42-R42): Updated the model reference in the `usageName` field for `text-embedding-ada-002` to `OpenAI.GlobalStandard.text-embedding-ada-002`.
* …

chore: migrate model type to global standard

---

infra/deploy_app_service.bicep
infra/main.json

* This pull request introduces updates to role assignments in the infrastructure deployment files. The changes ensure that the `principalType` property is explicitly set to `ServicePrincipal` for role assignments, enhancing clarity and alignment with best practices.
Updates to role assignments:
* [`infra/deploy_app_service.bicep`](diffhunk://#diff-37c8b5694d17291d641a19fb8a562e30642066b4bf8b8657f2636f50567cf4ebR335): Added the `principalType` property with the value `'ServicePrincipal'` to the `searchIndexDataReaderAssignment` role assignment.
* [`infra/main.json`](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L2081-R2082): Added the `principalType` property with the value `"ServicePrincipal"` to the role assignment for the …

fix: add principalType as 'ServicePrincipal' for role assignments

---

.github/workflows/deploy.yml
infra/main.bicep

This pull request modifies the logic for generating the `solutionPrefix` in the `infra/main.bicep` file to ensure consistency and uniqueness by incorporating additional parameters in the `uniqueString` function.
* Updated the `solutionPrefix` variable to use `toLower(uniqueString(subscription().id, environmentName, resourceGroup().location, resourceGroup().name))`, adding `resourceGroup().name` to enhance uniqueness and ensure the prefix is consistently derived from all relevant resource group details.## Purpose
* ...

fix: Prefix/Suffix fixes - dev to main

---

infra/deploy_ai_foundry.bicep
infra/deploy_foundry_role_assignment.bicep
infra/main.json

This pull request introduces support for deploying AI model configurations in the Azure Cognitive Services infrastructure. The changes primarily focus on adding a new parameter for AI model deployments and updating the deployment logic to handle these configurations and support for existing AI projects.
* Added a new `aiModelDeployments` parameter of type `array` in `infra/deploy_foundry_role_assignment.bicep` to define multiple AI model configurations.
* Introduced a new resource loop in `infra/deploy_foundry_role_assignment.bicep` to create deployments for each AI model in `aiModelDeployments`, including properties such as model name, RAI policy, and SKU details.
* Updated the `assignOpenAIRoleToAISearch` module in `infra/deploy_ai_foundry.bicep` to pass the `aiModelDeployments` …

fix: Model Deployment When Reusing Existing Foundry Service/Projects

---

infra/deploy_app_service.bicep
infra/main.bicep
infra/main.json
infra/scripts/index_scripts/requirements.txt
infra/scripts/run_create_index_scripts.sh
src/app.py
src/backend/api/agent/agent_factory_base.py
src/backend/api/agent/browse_agent_factory.py
src/backend/api/agent/section_agent_factory.py
src/backend/api/agent/template_agent_factory.py
src/backend/settings.py

This pull request introduces several enhancements and fixes across the infrastructure, backend, and scripts. The most notable changes include adding support for Azure AI Agent API versioning, improving application lifecycle management, refining citation handling in chat responses, and introducing a base factory class for agent management. Additionally, dependency versions have been pinned, and minor improvements have been made to scripts and JSON templates.
* Added a new parameter `azureAiAgentApiVersion` to support Azure AI Agent API versioning in `infra/deploy_app_service.bicep` and `infra/main.bicep`. The parameter is also reflected in `infra/main.json` for consistency. [[1]](diffhunk://#diff-37c8b5694d17291d641a19fb8a562e30642066b4bf8b8657f2636f50567cf4ebR34) …

feat: Agent and thread management

---

infra/main.bicep
infra/main.json

This pull request introduces several updates to the infrastructure deployment and application logic, focusing on improving AI model deployment capabilities, adding support for a new Azure AI Agent API version, enhancing region configurations, and refining Python dependencies and application lifecycle management.
* **AI Model Deployment Support**: Added support for specifying and deploying AI models via the `aiModelDeployments` parameter in `infra/deploy_foundry_role_assignment.bicep` and `infra/main.json`. This includes batch processing and configuration of model properties, RAI policies, and SKU settings.
* **Azure AI Agent API Version**: Introduced `azureAiAgentApiVersion` parameter to support the Azure AI Agent service, replacing `azureOpenAIApiVersion` where applicable. Updated …

fix: Added Validation for Supported regions for AI deployment location

---

docs/CustomizingAzdParameters.md

This update modifies the description for the AZURE_LOCATION parameter in the docs/CustomizingAzdParameters.md file to better reflect the dynamic nature of the value selection during deployment.
**Changes Made:**
Updated the default value for AZURE_LOCATION from a hardcoded japaneast to a more general description: "User selects during deployment".
This change helps clarify that the Azure region is selected during the deployment process, improving accuracy and flexibility.
- [x ] I have tested the primary workflows (the "golden path") to ensure they function correctly without errors.

docs: Update AZURE_LOCATION Parameter Description in Docs

---

src/frontend/package-lock.json
src/frontend/package.json

This pull request updates several frontend dependencies to their latest versions and introduces an override for the `form-data` package. The primary focus is on keeping the `react-router` and `react-router-dom` libraries up to date, as well as ensuring compatibility and security by updating `form-data`. Additionally, an unused dependency (`turbo-stream`) has been removed.
**Dependency updates:**
* Updated `react-router-dom` to version `^7.5.2` in both `package.json` and `package-lock.json` for improved features and bug fixes.
* Updated `react-router` to version `7.8.2` in `package-lock.json` for compatibility with the latest `react-router-dom`.
**Security and compatibility improvements:**
* Updated `form-data` to version `4.0.4` and added an explicit override in `package.json` to ensure …

chore: fixed security vulnerability

---

.github/workflows/deploy.yml
infra/scripts/process_sample_data.sh

This pull request updates the deployment workflow to improve environment variable handling, region selection, and post-deployment scripting for Azure resources. The changes enhance flexibility for regional deployments and ensure correct variable propagation during pipeline execution.
**Workflow trigger and environment handling:**
* Added support for triggering the workflow on pull requests to the `main` branch, allowing deployment tests on PRs.
* Improved region selection logic by setting `AZURE_AI_LOCATION` and updating `AZURE_LOCATION` based on specific region values, enabling more accurate deployment targeting.
**Deployment parameter updates:**
* Modified deployment parameters to dynamically use environment variables for locations and capacities, and replaced hardcoded values with …

ci: fix deploy pipeline

---

README.md
azure.yaml
docs/DeploymentGuide.md
infra/scripts/process_sample_data.sh

This pull request updates the minimum required version of the Azure Developer CLI (`azd`) to 1.18.0 across documentation and configuration files. It also adds clearer guidance for users to ensure they have the correct version installed before deploying the solution.
**Updates to required tooling and documentation:**
* Increased the minimum required version of `azd` from 1.15.0 to 1.18.0 in the `azure.yaml` configuration file to enforce compatibility.
* Updated all relevant documentation (`README.md` and `docs/DeploymentGuide.md`) to specify `azd` version 1.18.0+ as a requirement, replacing previous references to version 1.15.0. [[1]](diffhunk://#diff-5a9feaaa3fe70489e88e08725db341b9dafb6a4185d382bba81c4093aaaded7cL115-R115) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac0 …

docs: Updated README, azure.yml for minimum azd version 1.18.0
